### ISSUE TITLE
Completion menu navigation behaviour changed

### ISSUE THREAD

**Issue by bartlibert** [Shougo/deoplete-clangx#4]
# Problems summary
When this plugin is active, completion menu navigation with CTRL-N and CTRL-P does not work as expected. If the clangx plugin is enabled, but its results are not yet available in the menu (due to a large project e.g.), pressing "CTRL-N" or "CTRL-P" will insert the first element (from other, quicker completions) immediately and the menu is closed, making it impossible to navigate to other options. Note that when using arrow-up and arrow-down, it does work as expected. When the clangx completions are in the menu, everything works as expected.

## Expected
Navigation of the suggestions in the menu with CTRL-N and CTRL-P is possible and all options stay shown. Only when I type extra letters or select the suggestion, the menu is updated.

## Environment Information

 * deoplete version(SHA1): 3fb71d7
 * deoplete-clangx version(SHA1): c943ce0

 * OS:
Debian buster/sid

 * neovim/Vim `:version` output:
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 05 2018 16:15:22)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +byte_offset       +comments          +digraphs          +file_in_path      +iconv             +linebreak         +mouse             +mouse_urxvt       +path_extra        +quickfix          +statusline        +terminal          +vertsplit         +windows           -xterm_save
+arabic            +channel           +conceal           -dnd               +find_in_path      +insert_expand     +lispindent        -mouseshape        +mouse_xterm       +perl              +reltime           -sun_workshop      +terminfo          +virtualedit       +writebackup
+autocmd           +cindent           +cryptv            -ebcdic            +float             +job               +listcmds          +mouse_dec         +multi_byte        +persistent_undo   +rightleft         +syntax            +termresponse      +visual            -X11
-autoservername    -clientserver      +cscope            +emacs_tags        +folding           +jumplist          +localmap          +mouse_gpm         +multi_lang        +postscript        +ruby              +tag_binary        +textobjects       +visualextra       -xfontset
-balloon_eval      -clipboard         +cursorbind        +eval              -footer            +keymap            +lua               -mouse_jsbterm     -mzscheme          +printer           +scrollbind        +tag_old_static    +timers            +viminfo           -xim
+balloon_eval_term +cmdline_compl     +cursorshape       +ex_extra          +fork()            +lambda            +menu              +mouse_netterm     +netbeans_intg     +profile           +signs             -tag_any_white     +title             +vreplace          -xpm
-browse            +cmdline_hist      +dialog_con        +extra_search      +gettext           +langmap           +mksession         +mouse_sgr         +num64             -python            +smartindent       +tcl               -toolbar           +wildignore        -xsmp
++builtin_terms    +cmdline_info      +diff              +farsi             -hangul_input      +libcall           +modify_fname      -mouse_sysmouse    +packages          +python3           +startuptime       +termguicolors     +user_commands     +wildmenu          -xterm_clipboard
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-gh7zee/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/C
ORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm
`
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let s:deinpath = $HOME . '/.vim/dein/repos/github.com/Shougo/dein.vim'
execute 'set runtimepath+='.s:deinpath
call dein#begin(expand('~/.cache/dein'))
call dein#add(expand('~/.vim/dein/repos/github.com/Shougo/dein.vim/'), { 'name': 'dein' })
call dein#add('Shougo/deoplete.nvim', { 'name': 'deoplete' })
if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
endif
call dein#add('Shougo/deoplete-clangx', {
            \ 'name': 'deoplete-clangx',
            \ 'depends': 'deoplete',
            \'on_ft': ['c', 'cpp']
            \ })
call dein#end()
if dein#check_install()
    call dein#install()
    call dein#recache_runtimepath()
endif


filetype plugin indent on
syntax enable
```

### Failure scenario:
 1. Apply the patch from [this comment](https://github.com/Shougo/deoplete-clangx/issues/4#issuecomment-388845240)
2. Save the example source file to /tmp/test.cpp (name does not really matter)
3. Open /tmp/test.cpp in (n)vim
4. :call deoplete#enable()
5. Put the cursor on line 7 and press "O"
6. Type "std::"
7. You will now get a menu with some completions, namely "endl, string and cout"
8. Press "Ctrl-N" -> The first result will immediately be inserted, instead of navigation to different posibilities.
[![asciicast](https://asciinema.org/a/NpBpDYLsDXB5LPTEOpypNXpSn.png)](https://asciinema.org/a/NpBpDYLsDXB5LPTEOpypNXpSn)

[![asciicast](https://asciinema.org/a/3PQMmCJh1PmKZwuYdMcEQNcYm.png)](https://asciinema.org/a/3PQMmCJh1PmKZwuYdMcEQNcYm)

### Working scenario 1:
1. Repeat steps 1-7 from failure scenario
2. Use arrow keys instead of CTRL-N/CTRL-P
[![asciicast](https://asciinema.org/a/tcGLiUikILifYv7Isba4XAP78.png)](https://asciinema.org/a/tcGLiUikILifYv7Isba4XAP78)

### Working scenario 2:
1. Repeat steps 1-7 from failure scenario
2. Wait for completions from clangx to appear
3. Navigate with "CTRL-N/CTRL-P"
[![asciicast](https://asciinema.org/a/ZE5SL4ixUgXBnCvUYy8v3daRR.png)](https://asciinema.org/a/ZE5SL4ixUgXBnCvUYy8v3daRR)

## Example source file
```
#include <iostream>
#include <string>

int main()
{
    std::string test = "test";
    std::cout << test << std::endl;
    return 0;
}
```

## Screen shot (if possible)
Not working:
[![asciicast](https://asciinema.org/a/DizugEiIwZT2G1iwHiULfMOwF.png)](https://asciinema.org/a/DizugEiIwZT2G1iwHiULfMOwF)

Expected behaviour: 
[![asciicast](https://asciinema.org/a/OvdpKoVqvD9upiMawLRJUcM6Z.png)](https://asciinema.org/a/OvdpKoVqvD9upiMawLRJUcM6Z)

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/749

**Comment by Shougo** [comment]
I think the problem is already fixed...
Your deoplete version is really latest?

I will test it later.

**Comment by Shougo** [comment]
> Open c++ file in large project (this is necessary so the completions from clangx take some time to appear, might be reproducible by delaying them artificially as well)

Please provide the large project example.
I must reproduce the problem.

**Comment by bartlibert** [comment]
I double checked and I am on deoplete version 3fb71d7, which seems to be the latest as far as I can see.

I cannot share the project as it contains proprietary code from my employer, but I'll try to see if I can create something similar. I do have a doubt though that this will be consistently reproducible, as I guess it is also related to the system.

I found another way to reproduce the behaviour, although it is a bit hacky, so if you object to this, no problem, I'll try to make a project nonetheless.

The "hack to reproduce" is to create a shell script containing the following contents:

```
#!/bin/sh
sleep 4
clang "$@"
```
I saved this as ~/bin/my_clang.sh, but it can be anywhere, as long as it's executable.

Then, in my .vimrc I put (replace with the relevant filename)
`call deoplete#custom#var('clangx', 'clang_binary', '/home/username/bin/my_clang.sh')`

Now, I can reproduce it in any simple c++ project

**Comment by Shougo** [comment]
Please use the latest version of deoplete.

**Comment by bartlibert** [comment]
I still see this behaviour with the last version of deoplete (master branch). Is there some other "latest" version I should use (other branch?)

**Comment by Shougo** [comment]
Really?
I cannot reproduce the problem.

https://github.com/Shougo/deoplete-clangx/issues/4#issuecomment-386986505

```diff
diff --git a/rplugin/python3/deoplete/source/clangx.py b/rplugin/python3/deoplete/source/clangx.py
index 798c59c..07ddca3 100644
--- a/rplugin/python3/deoplete/source/clangx.py
+++ b/rplugin/python3/deoplete/source/clangx.py
@@ -8,6 +8,7 @@ import os.path
 import subprocess
 import shlex
 from itertools import chain
+import time

 from deoplete.util import getlines, error
 from .base import Base
@@ -49,6 +50,8 @@ class Source(Base):
         return m.start() if m else -1

     def gather_candidates(self, context):
+        time.sleep(5.0)
+
         if not self.executable_clang:
             return []

```

I think it is same behavior.  But I cannot reproduce it.

**Comment by Shougo** [comment]
And, 

* Your Vim is not the latest version.  Please use the latest version.
* Please test neovim instead.

**Comment by Shougo** [comment]
If you test the both patterns and with above clang-x patch, I will test it again.
If not, I will ignore your report.

**Comment by Shougo** [comment]
I have reproduced the older branch + Vim8 with the behavior.
But in the latest version or neovim, I cannot reproduce it.

**Comment by bartlibert** [comment]
With the patch above in clangx, I can reproduce it in vim 8.0.1842 and in neovim v0.3.0-1231-gefb6caa39

**Comment by Shougo** [comment]
OK.  If so I must test it again.

But please upload the reproduce steps like this.
https://github.com/Shougo/deoplete.nvim/issues/754

If you don't upload it, I will ignore your issue.

I wait.

**Comment by Shougo** [comment]
> Now, I can reproduce it in any simple c++ project

It is very fuzzy steps.
We have not ESP skills

The reproduce steps must be reproduce-able in every person.

**Comment by bartlibert** [comment]
I have updated the reproduction scenario in the OP

**Comment by Shougo** [comment]
OK.
Finally, I have reproduced the problem.
It seems hard to fix.
Please wait.

**Comment by bartlibert** [comment]
No problem, take your time. Sorry for the unclear reproduction steps at first.

**Comment by Shougo** [comment]
Please test the latest deoplete.
